// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/checkconfig.proto

// Package checkconfig represents an attestation validation policy.

package checkconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Policy is a representation of an attestation quote validation policy.
// Each field corresponds to a field on validate.Options. This format
// is useful for providing programmatic inputs to the `check` CLI tool.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HeaderPolicy is representation of Header of an attestation quote validation
	// policy.
	HeaderPolicy *HeaderPolicy `protobuf:"bytes,1,opt,name=header_policy,json=headerPolicy,proto3" json:"header_policy,omitempty"` // should be 20 bytes
	// TDQuoteBodyPolicy is representation of TdQuoteBody of an attestation quote
	// validation policy.
	TdQuoteBodyPolicy *TDQuoteBodyPolicy `protobuf:"bytes,2,opt,name=td_quote_body_policy,json=tdQuoteBodyPolicy,proto3" json:"td_quote_body_policy,omitempty"` // should be 528 bytes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_proto_checkconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_proto_checkconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetHeaderPolicy() *HeaderPolicy {
	if x != nil {
		return x.HeaderPolicy
	}
	return nil
}

func (x *Policy) GetTdQuoteBodyPolicy() *TDQuoteBodyPolicy {
	if x != nil {
		return x.TdQuoteBodyPolicy
	}
	return nil
}

type HeaderPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinimumQeSvn  uint32                 `protobuf:"varint,1,opt,name=minimum_qe_svn,json=minimumQeSvn,proto3" json:"minimum_qe_svn,omitempty"`    // should not exceed uint16 max
	MinimumPceSvn uint32                 `protobuf:"varint,2,opt,name=minimum_pce_svn,json=minimumPceSvn,proto3" json:"minimum_pce_svn,omitempty"` // should not exceed uint16 max
	// Unique vendor id of QE vendor
	QeVendorId    []byte `protobuf:"bytes,3,opt,name=qe_vendor_id,json=qeVendorId,proto3" json:"qe_vendor_id,omitempty"` // should be 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderPolicy) Reset() {
	*x = HeaderPolicy{}
	mi := &file_proto_checkconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPolicy) ProtoMessage() {}

func (x *HeaderPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPolicy.ProtoReflect.Descriptor instead.
func (*HeaderPolicy) Descriptor() ([]byte, []int) {
	return file_proto_checkconfig_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderPolicy) GetMinimumQeSvn() uint32 {
	if x != nil {
		return x.MinimumQeSvn
	}
	return 0
}

func (x *HeaderPolicy) GetMinimumPceSvn() uint32 {
	if x != nil {
		return x.MinimumPceSvn
	}
	return 0
}

func (x *HeaderPolicy) GetQeVendorId() []byte {
	if x != nil {
		return x.QeVendorId
	}
	return nil
}

type TDQuoteBodyPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MinimumTeeTcbSvn []byte                 `protobuf:"bytes,1,opt,name=minimum_tee_tcb_svn,json=minimumTeeTcbSvn,proto3" json:"minimum_tee_tcb_svn,omitempty"` // should be 16 bytes
	MrSeam           []byte                 `protobuf:"bytes,2,opt,name=mr_seam,json=mrSeam,proto3" json:"mr_seam,omitempty"`                                   // should be 48 bytes
	TdAttributes     []byte                 `protobuf:"bytes,3,opt,name=td_attributes,json=tdAttributes,proto3" json:"td_attributes,omitempty"`                 // should be 8 bytes
	Xfam             []byte                 `protobuf:"bytes,4,opt,name=xfam,proto3" json:"xfam,omitempty"`                                                     // should be 8 bytes
	MrTd             []byte                 `protobuf:"bytes,5,opt,name=mr_td,json=mrTd,proto3" json:"mr_td,omitempty"`                                         // should be 48 bytes
	MrConfigId       []byte                 `protobuf:"bytes,6,opt,name=mr_config_id,json=mrConfigId,proto3" json:"mr_config_id,omitempty"`                     // should be 48 bytes
	MrOwner          []byte                 `protobuf:"bytes,7,opt,name=mr_owner,json=mrOwner,proto3" json:"mr_owner,omitempty"`                                // should be 48 bytes
	MrOwnerConfig    []byte                 `protobuf:"bytes,8,opt,name=mr_owner_config,json=mrOwnerConfig,proto3" json:"mr_owner_config,omitempty"`            // should be 48 bytes
	Rtmrs            [][]byte               `protobuf:"bytes,9,rep,name=rtmrs,proto3" json:"rtmrs,omitempty"`                                                   // should be 48 * rtmrsCount
	ReportData       []byte                 `protobuf:"bytes,10,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`                      // should be 64 bytes
	AnyMrTd          [][]byte               `protobuf:"bytes,11,rep,name=any_mr_td,json=anyMrTd,proto3" json:"any_mr_td,omitempty"`                             // each should be 48 bytes.
	// Expected value of the DEBUG bit in td_attributes.
	TdattributesDebug *bool `protobuf:"varint,12,opt,name=tdattributes_debug,json=tdattributesDebug,proto3,oneof" json:"tdattributes_debug,omitempty"` // Expected value of the DEBUG bit in td_attributes.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TDQuoteBodyPolicy) Reset() {
	*x = TDQuoteBodyPolicy{}
	mi := &file_proto_checkconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TDQuoteBodyPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TDQuoteBodyPolicy) ProtoMessage() {}

func (x *TDQuoteBodyPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TDQuoteBodyPolicy.ProtoReflect.Descriptor instead.
func (*TDQuoteBodyPolicy) Descriptor() ([]byte, []int) {
	return file_proto_checkconfig_proto_rawDescGZIP(), []int{2}
}

func (x *TDQuoteBodyPolicy) GetMinimumTeeTcbSvn() []byte {
	if x != nil {
		return x.MinimumTeeTcbSvn
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetMrSeam() []byte {
	if x != nil {
		return x.MrSeam
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetTdAttributes() []byte {
	if x != nil {
		return x.TdAttributes
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetXfam() []byte {
	if x != nil {
		return x.Xfam
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetMrTd() []byte {
	if x != nil {
		return x.MrTd
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetMrConfigId() []byte {
	if x != nil {
		return x.MrConfigId
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetMrOwner() []byte {
	if x != nil {
		return x.MrOwner
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetMrOwnerConfig() []byte {
	if x != nil {
		return x.MrOwnerConfig
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetRtmrs() [][]byte {
	if x != nil {
		return x.Rtmrs
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetReportData() []byte {
	if x != nil {
		return x.ReportData
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetAnyMrTd() [][]byte {
	if x != nil {
		return x.AnyMrTd
	}
	return nil
}

func (x *TDQuoteBodyPolicy) GetTdattributesDebug() bool {
	if x != nil && x.TdattributesDebug != nil {
		return *x.TdattributesDebug
	}
	return false
}

// RootOfTrust represents configuration for which hardware root of trust
// certificates to use for verifying attestation quote.
type RootOfTrust struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paths to CA bundles for the Intel TDX.
	// Must be in PEM format.
	// If empty, uses the verification library's embedded certificates from Intel.
	CabundlePaths []string `protobuf:"bytes,1,rep,name=cabundle_paths,json=cabundlePaths,proto3" json:"cabundle_paths,omitempty"`
	// PEM format CA bundles for Intel TDX. Combined with contents of
	// cabundle_paths.
	Cabundles []string `protobuf:"bytes,2,rep,name=cabundles,proto3" json:"cabundles,omitempty"`
	// If true, download and check the CRL for revoked certificates.
	CheckCrl bool `protobuf:"varint,3,opt,name=check_crl,json=checkCrl,proto3" json:"check_crl,omitempty"`
	// If true, then check is not permitted to download necessary files for
	// verification.
	GetCollateral bool `protobuf:"varint,4,opt,name=get_collateral,json=getCollateral,proto3" json:"get_collateral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootOfTrust) Reset() {
	*x = RootOfTrust{}
	mi := &file_proto_checkconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootOfTrust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootOfTrust) ProtoMessage() {}

func (x *RootOfTrust) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootOfTrust.ProtoReflect.Descriptor instead.
func (*RootOfTrust) Descriptor() ([]byte, []int) {
	return file_proto_checkconfig_proto_rawDescGZIP(), []int{3}
}

func (x *RootOfTrust) GetCabundlePaths() []string {
	if x != nil {
		return x.CabundlePaths
	}
	return nil
}

func (x *RootOfTrust) GetCabundles() []string {
	if x != nil {
		return x.Cabundles
	}
	return nil
}

func (x *RootOfTrust) GetCheckCrl() bool {
	if x != nil {
		return x.CheckCrl
	}
	return false
}

func (x *RootOfTrust) GetGetCollateral() bool {
	if x != nil {
		return x.GetCollateral
	}
	return false
}

// Config is the overall message input for the check tool. This provides all
// the flags that configure the tool, including the validation policy.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The report validation policy.
	Policy *Policy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// Configures which hardware keys to trust. Default uses library-embedded
	// certificate.
	RootOfTrust   *RootOfTrust `protobuf:"bytes,2,opt,name=root_of_trust,json=rootOfTrust,proto3" json:"root_of_trust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_checkconfig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkconfig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_checkconfig_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Config) GetRootOfTrust() *RootOfTrust {
	if x != nil {
		return x.RootOfTrust
	}
	return nil
}

var File_proto_checkconfig_proto protoreflect.FileDescriptor

const file_proto_checkconfig_proto_rawDesc = "" +
	"\n" +
	"\x17proto/checkconfig.proto\x12\vcheckconfig\"\x99\x01\n" +
	"\x06Policy\x12>\n" +
	"\rheader_policy\x18\x01 \x01(\v2\x19.checkconfig.HeaderPolicyR\fheaderPolicy\x12O\n" +
	"\x14td_quote_body_policy\x18\x02 \x01(\v2\x1e.checkconfig.TDQuoteBodyPolicyR\x11tdQuoteBodyPolicy\"~\n" +
	"\fHeaderPolicy\x12$\n" +
	"\x0eminimum_qe_svn\x18\x01 \x01(\rR\fminimumQeSvn\x12&\n" +
	"\x0fminimum_pce_svn\x18\x02 \x01(\rR\rminimumPceSvn\x12 \n" +
	"\fqe_vendor_id\x18\x03 \x01(\fR\n" +
	"qeVendorId\"\xac\x03\n" +
	"\x11TDQuoteBodyPolicy\x12-\n" +
	"\x13minimum_tee_tcb_svn\x18\x01 \x01(\fR\x10minimumTeeTcbSvn\x12\x17\n" +
	"\amr_seam\x18\x02 \x01(\fR\x06mrSeam\x12#\n" +
	"\rtd_attributes\x18\x03 \x01(\fR\ftdAttributes\x12\x12\n" +
	"\x04xfam\x18\x04 \x01(\fR\x04xfam\x12\x13\n" +
	"\x05mr_td\x18\x05 \x01(\fR\x04mrTd\x12 \n" +
	"\fmr_config_id\x18\x06 \x01(\fR\n" +
	"mrConfigId\x12\x19\n" +
	"\bmr_owner\x18\a \x01(\fR\amrOwner\x12&\n" +
	"\x0fmr_owner_config\x18\b \x01(\fR\rmrOwnerConfig\x12\x14\n" +
	"\x05rtmrs\x18\t \x03(\fR\x05rtmrs\x12\x1f\n" +
	"\vreport_data\x18\n" +
	" \x01(\fR\n" +
	"reportData\x12\x1a\n" +
	"\tany_mr_td\x18\v \x03(\fR\aanyMrTd\x122\n" +
	"\x12tdattributes_debug\x18\f \x01(\bH\x00R\x11tdattributesDebug\x88\x01\x01B\x15\n" +
	"\x13_tdattributes_debug\"\x96\x01\n" +
	"\vRootOfTrust\x12%\n" +
	"\x0ecabundle_paths\x18\x01 \x03(\tR\rcabundlePaths\x12\x1c\n" +
	"\tcabundles\x18\x02 \x03(\tR\tcabundles\x12\x1b\n" +
	"\tcheck_crl\x18\x03 \x01(\bR\bcheckCrl\x12%\n" +
	"\x0eget_collateral\x18\x04 \x01(\bR\rgetCollateral\"s\n" +
	"\x06Config\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.checkconfig.PolicyR\x06policy\x12<\n" +
	"\rroot_of_trust\x18\x02 \x01(\v2\x18.checkconfig.RootOfTrustR\vrootOfTrustB2Z0github.com/google/go-tdx-guest/proto/checkconfigb\x06proto3"

var (
	file_proto_checkconfig_proto_rawDescOnce sync.Once
	file_proto_checkconfig_proto_rawDescData []byte
)

func file_proto_checkconfig_proto_rawDescGZIP() []byte {
	file_proto_checkconfig_proto_rawDescOnce.Do(func() {
		file_proto_checkconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_checkconfig_proto_rawDesc), len(file_proto_checkconfig_proto_rawDesc)))
	})
	return file_proto_checkconfig_proto_rawDescData
}

var file_proto_checkconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_checkconfig_proto_goTypes = []any{
	(*Policy)(nil),            // 0: checkconfig.Policy
	(*HeaderPolicy)(nil),      // 1: checkconfig.HeaderPolicy
	(*TDQuoteBodyPolicy)(nil), // 2: checkconfig.TDQuoteBodyPolicy
	(*RootOfTrust)(nil),       // 3: checkconfig.RootOfTrust
	(*Config)(nil),            // 4: checkconfig.Config
}
var file_proto_checkconfig_proto_depIdxs = []int32{
	1, // 0: checkconfig.Policy.header_policy:type_name -> checkconfig.HeaderPolicy
	2, // 1: checkconfig.Policy.td_quote_body_policy:type_name -> checkconfig.TDQuoteBodyPolicy
	0, // 2: checkconfig.Config.policy:type_name -> checkconfig.Policy
	3, // 3: checkconfig.Config.root_of_trust:type_name -> checkconfig.RootOfTrust
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_checkconfig_proto_init() }
func file_proto_checkconfig_proto_init() {
	if File_proto_checkconfig_proto != nil {
		return
	}
	file_proto_checkconfig_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_checkconfig_proto_rawDesc), len(file_proto_checkconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_checkconfig_proto_goTypes,
		DependencyIndexes: file_proto_checkconfig_proto_depIdxs,
		MessageInfos:      file_proto_checkconfig_proto_msgTypes,
	}.Build()
	File_proto_checkconfig_proto = out.File
	file_proto_checkconfig_proto_goTypes = nil
	file_proto_checkconfig_proto_depIdxs = nil
}
